### ISSUE TITLE
Hangouts failing to connect

### ISSUE THREAD

**Issue by da4089** [meetfranz/recipe-hangouts#15]
Starting 2020/11/02, my Hangouts is unable to connect.  It works in Firefox, but not Franz.

![Screen Shot 2020-11-04 at 09 22 42](https://user-images.githubusercontent.com/860066/98047052-617a0a80-1e7f-11eb-886a-188e0a14e927.png)

Any debugging hints?

**Comment by chucksense** [comment]
Works fine in Chrome as well, but still won't work in Franz.

**Comment by chucksense** [comment]
@da4089 a heads up that it turned out I was using an older version of Franz (5.3.3) and using Check for Updates was not returning any updates.  So I went to [their homepage](https://meetfranz.com) downloaded the latest version (5.5.0) installed it, then signed out the Hangouts service and signed back in, and everything is now working.

**Comment by da4089** [comment]
I'm using Franz v5.5.0.1762 on macOS 10.14.6 (Mojave).

**Comment by da4089** [comment]
I was able to fix this.  Foloowing @chucksense 's suggestion, I signed out of my Google account within Franz, then logged in again, and then reloaded the Hangouts page (Command-R).  This appears to have resolved the problem.

Thanks!
